FROM node:16

ENV NODE_ENV development

WORKDIR /app
COPY ./package.json ./yarn.lock /app/
RUN yarn install
# --immutable --immutable-cache --check-cache

ARG NODE_ENV=production
ENV NODE_ENV ${NODE_ENV}

COPY ./ /app/

CMD yarn run start