FROM node:16

ARG NODE_ENV=production
ENV NODE_ENV ${NODE_ENV}

WORKDIR /app
COPY ./package.json ./yarn.lock /app/
RUN yarn install
# --immutable --immutable-cache --check-cache


COPY ./ /app/

CMD yarn run start