FROM ubuntu:latest

RUN apt-get update -y
RUN apt-get install -y curl

WORKDIR /app
COPY ./backend/setup.sh /app/
COPY ./backend/schema.graphql /app/

ARG DEPLOYMENT_URL=http://dgraph:8080
ENV DEPLOYMENT_URL ${DEPLOYMENT_URL}

CMD bash ./setup.sh